FROM python:3.11.6-slim

WORKDIR /backend

COPY backend/requirements.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY backend/ .
COPY shared/ /shared

ENV PYTHONPATH="/:/backend"

CMD ["uvicorn", "app_backend.main:app", "--host", "0.0.0.0", "--port", "3000", "--lifespan", "on"]
